service: stickerify-tgbot
useDotenv: true
configValidationMode: error
frameworkVersion: '>=3.23.0'

provider:
  region: "eu-central-1"
  name: aws
  runtime: go1.x
  logRetentionInDays: 30
  endpointType: regional
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "xray:*"

package:
  patterns:
    - "bin/webhook"

functions:
  webhook:
    handler: bin/webhook
    timeout: 30
    description: telegram image converter and resizer
    memorySize: 128
    environment:
      TELEGRAM_TOKEN: ${env:TELEGRAM_TOKEN}

    events:
      - http:
          path: /webhook
          method: ANY
          cors: false
